#
# production settings
# 
# (version: 11, saved: 2021-04-22 23:24:35)
#
---
production:
  settings:
    id: riviacapital
    caption: City of Rivia
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 5115
    strings-idstart: 0
    version: 11
    mounters:
      - ".type": CR4MappinsDLCMounter
        worldFilePath: "dlc\\dlcriviacapital\\levels\\riviacapital\\riviacapital.w2w"
        mappinsFilePath: "dlc\\dlcriviacapital\\data\\hub_pins\\riviacapital.w2em"
      - ".type": CR4ScaleformContentDLCMounter
        scaleformDirectoryPath: "dlc\\dlcriviacapital\\data\\gameplay\\gui_new\\"
      - ".type": CR4WorldDLCMounter
        worlds:
          riviacapital:
            hubSlotId: AN_TestHubSlot_13
            worldMapCaption: City of Rivia
            worldMapDescription: "An impregnable stronghold and capital of the Rivia region, which once hosted one of history's bloodiest non-human pogroms in 1268. It is enjoying its independence during a period of tumult for the Northern Realms."
            worldMapPosition:
              - 500
              - 500
            worldMapSuggestedLevel: 42
            worldMapPath: "dlc\\dlcriviacapital\\levels\\riviacapital\\riviacapital.w2w"
            worldMiniMapSize: 4000.0
            worldMiniMapTileCount: 16
            worldMiniMapExteriorTextureSize: 512
            worldMiniMapInteriorTextureSize: 2048
            worldMiniMapTextureSize: 1024
            worldMiniMapMinLod: 1
            worldMiniMapMaxLod: 3
            worldMiniMapExteriorTextureExtension: jpg
            worldMiniMapInteriorTextureExtension: png

            ### HUB CENTER = (-324.487, 92.7805), inscribed CIRCLE RADIUS = 1037 - useless info
            ### MIN x = -1388 MAX x = 791  DIFF = 2179
            ### MIN y = -1659 MAX y = 1684 DIFF = 3343
            worldMiniMapVminX: -850  # use hub map MIN-MAX coordinates CONVERTED into pixels (coordinate * 1024 / 2000)
            worldMiniMapVmaxX: 750
            worldMiniMapVminY: -970
            worldMiniMapVmaxY: 970
            worldMiniMapSminX: -410    # map movement size
            worldMiniMapSmaxX: 360
            worldMiniMapSminY: -500
            worldMiniMapSmaxY: 400
            worldMiniMapMinZoom: 0.9
            worldMiniMapMaxZoom: 4.0
            worldMiniMapZoom12: 1.5
            worldMiniMapZoom23: 2.6
            worldMiniMapZoom34: -1.0
            worldGradientScale: 1.0
            worldPreviewHeight: 1.0
